config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  resources :visions
  root "visions#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :visions
end

app/models/vision.rb
class Vision < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visions_controller.rb
class VisionsController < ApplicationController
  before_action :find_vision, only: [:show, :edit, :update, :destroy]

  # index to hold the visions
  def index
    @visions = Vision.all.order("created_at DESC")
  end

  #show visions
  def show
  end

  # new visions
  def new
    @vision = current_user.visions.build
  end

  # create visions
  def create
    @vision = current_user.visions.build(vision_params)

    if @vision.save
      redirect_to @vision, notice: "You made a new Vision!"
    else
      render 'new'
    end
  end

  #edit visions
  def edit
  end

  #update visions
  def update
    if @vision.update(vision_params)
      redirect_to @vision, notice: "You successfully updated your Vision!"
    else
      render 'edit'
    end
  end

  #delete visions
  def destroy
    @vision.destroy
    redirect_to root_path
  end

  private

  def vision_params
    params.require(:vision).permit(:title, :description)
  end

  def find_vision
    @vision = Vision.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visions_helper.rb
module VisionsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Vision Board
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Vision Board", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Vision", new_vision_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      -else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = yield

app/views/visions/_form.html.haml
= simple_form_for @vision, html: { multipart: true } do |f|
  - if @vision.errors.any?
    #errors
      %h2
      = pluralize(@vision.errors.count, "error")
      prevented this Vision from saving
      %ul
        - @vision.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :title, input_html: { class: 'form-control' }

  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: "btn btn-primary"

app/views/visions/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Vision
  = render 'form'
  = link_to "Cancel", vision_path

app/views/visions/index.html.haml
- @visions.each do |vision|
  %h2= link_to vision.title, vision

app/views/visions/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Form
  = render 'form'
  = link_to "Back", root_path

app/views/visions/show.html.haml
%h1= @vision.title
%p= @vision.description
%p
Submitted by
= @vision.user.email

%br/

= link_to "Back", root_path
= link_to "Edit", edit_vision_path
= link_to "Delete", vision_path, method: :delete, data: { confirm: "Are you sure? This action cannot be undone!" }